USE DataWarehouse;
GO
-----------------------------------------
--Database Exploration
-----------------------------------------
--Explore all the objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES;
--Explore all the columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customer';
-----------------------------------------
--Database Exploration
-----------------------------------------
--Explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customer;
--Explore all categories "the major divisions"
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_product
ORDER BY 1,2,3;
-----------------------------------------
--Date Exploration
-----------------------------------------
--Find the first and last order date in the fact_sales table
--How many years of sales are available
/*
SELECT TOP  1 order_date AS first_order_date FROM gold.fact_sales
WHERE order_date IS NOT NULL
ORDER BY order_date ASC;

SELECT TOP  1 order_date AS first_order_date FROM gold.fact_sales
WHERE order_date IS NOT NULL
ORDER BY order_date DESC;
*/
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS months_of_sales
FROM gold.fact_sales;
--find the youngest and oldest customers
SELECT 
    MIN(birth_date) AS youngest_customer,
    DATEDIFF(YEAR, MIN(birth_date), GETDATE()) AS youngest_customer_age,
    MAX(birth_date) AS oldest_customer,
    DATEDIFF(YEAR, MAX(birth_date), GETDATE()) AS oldest_customer_age
FROM gold.dim_customer;
-----------------------------------------
--Measure Exploration
-----------------------------------------
--Find the total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales;
--Find how many items were sold
SELECT SUM(quantity) AS total_items_sold FROM gold.fact_sales;
--Find the average selling price
SELECT AVG(price) AS average_price FROM gold.fact_sales;
--Find the total number of orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales;
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales;
--Find the total number of products
SELECT COUNT(product_name) AS total_products FROM gold.dim_product;
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_product;
--Find the total number of customers
SELECT COUNT(customer_number) AS total_customers FROM gold.dim_customer;
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.dim_customer;
--Find the total number of customers who placed placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;
--Generate a report that shows all the key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS value FROM gold.fact_sales
UNION ALL
SELECT 'Total Number of Orders' AS measure_name, COUNT(DISTINCT order_number) AS value FROM gold.fact_sales
UNION ALL
SELECT 'Total Number of Products' AS measure_name, COUNT(DISTINCT product_key) AS value FROM gold.dim_product
UNION ALL
SELECT 'Total Number of Customers' AS measure_name, COUNT(DISTINCT customer_key) AS value FROM gold.dim_customer;
-----------------------------------------
--Magnitude Analysis
-----------------------------------------
--Find total customers by country
SELECT country, COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customer
GROUP BY country
ORDER BY total_customers DESC;
--Find total customers by gender
SELECT gender,COUNT(DISTINCT customer_key) AS total_customer_by_gender
FROM gold.dim_customer
GROUP BY gender
ORDER BY total_customer_by_gender DESC;
--Find total products by category
SELECT category,COUNT(DISTINCT product_key) AS total_products_by_category
FROM gold.dim_product
GROUP BY category
ORDER BY total_products_by_category DESC;
--What is the average cost in each category?
SELECT category,AVG(cost) AS average_cost_by_category
FROM gold.dim_product
GROUP BY category
ORDER BY average_cost_by_category DESC;
--What is the total revenue generated for each category
SELECT
    dp.category,
    SUM(fs.sales_amount) total_revenue_by_category
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_product AS dp ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue_by_category DESC;
--What is the revenue generated by each customer
SELECT
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    SUM(fs.sales_amount) total_revenue_by_customer
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customer AS dc ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key,
         dc.first_name,
         dc.last_name
ORDER BY total_revenue_by_customer DESC;
--What is the distribution of sold items across countries
SELECT
    dc.country,
    count(fs.product_key) number_of_sold_items
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customer AS dc ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY number_of_sold_items DESC;
/*
SELECT
    dc.country,
    dp.category,
    count(fs.product_key) number_of_sold_items
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customer AS dc ON fs.customer_key = dc.customer_key
LEFT JOIN gold.dim_product AS dp ON fs.product_key = dp.product_key
GROUP BY dc.country,
         dp.category
ORDER BY country, number_of_sold_items DESC;
*/
-----------------------------------------
--Ranking Analysis
-----------------------------------------
--Which 5 products generate the highest reveneu?
SELECT TOP 5
    dp.product_name,
    SUM(fs.sales_amount) total_revenue_by_product
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_product AS dp ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_revenue_by_product DESC;
/*
SELECT *
FROM
    (SELECT
        dp.product_name,
        SUM(fs.sales_amount) AS total_revenue_by_product,
        ROW_NUMBER() OVER(ORDER BY SUM(fs.sales_amount) DESC) rank_of_product
    FROM gold.fact_sales AS fs
    LEFT JOIN gold.dim_product AS dp ON fs.product_key = dp.product_key
    GROUP BY dp.product_name) AS subquery
WHERE rank_of_product <= 5;
*/
--Which 5 products generate the lowest reveneu?
SELECT TOP 5
    dp.product_name,
    SUM(fs.sales_amount) total_revenue_by_product
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_product AS dp ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_revenue_by_product ASC;
--Find the top 10 customers who have generated the highest revenue
SELECT TOP 5
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    SUM(fs.sales_amount) total_revenue_by_customer
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customer AS dc ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key,
         dc.first_name,
         dc.last_name
ORDER BY total_revenue_by_customer DESC;
--The 3 customers wih the fewest orders placed
SELECT TOP 3
    dc.customer_key,
    dc.first_name,
    dc.last_name,
    COUNT(DISTINCT fs.order_number) total_number_of_orders_by_customer
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customer AS dc ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key,
         dc.first_name,
         dc.last_name
ORDER BY total_number_of_orders_by_customer ASC;